"""
Prompt Builder — Location Insight -> GenAI Image-Gen Prompt
Rule-based assembly (see PROMPT_TEMPLATE_DESIGN.md for the mapping table).

Reads the dummy datasets generated by generate_dummy_data.py, computes a
location insight profile per outlet (nearest-catchment demographics,
competitor density, dominant daypart, occasion flag), then assembles a
structured prompt ready to send to the existing GenAI image-gen service.

Run:  python3 prompt_builder.py
"""

import math
import os
import pandas as pd
from collections import Counter

DATA_DIR = os.path.dirname(__file__)


# ---------------------------------------------------------------------------
# Geo helper
# ---------------------------------------------------------------------------
def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlmb = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dlmb / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


# ---------------------------------------------------------------------------
# 1. Build the location insight profile for one outlet
# ---------------------------------------------------------------------------
def build_insight_profile(outlet, demographics_df, competitors_df, foot_traffic_df,
                           radius_km=3.0, competitor_radius_km=3.0):
    lat, lon, brand = outlet["latitude"], outlet["longitude"], outlet["brand"]

    # --- nearby demographics (fallback to city-level if radius is empty —
    #     expected with fully synthetic scatter; real deployment would use
    #     a proper spatial join on aligned grid data) ---
    same_city = demographics_df[demographics_df["city"] == outlet["city"]].copy()
    same_city["dist_km"] = same_city.apply(
        lambda r: haversine_km(lat, lon, r["centroid_lat"], r["centroid_lon"]), axis=1
    )
    nearby = same_city[same_city["dist_km"] <= radius_km]
    pool = nearby if len(nearby) >= 3 else same_city  # fallback: city-level aggregate

    dominant_income = Counter(pool["income_bracket"]).most_common(1)[0][0]
    dominant_land_use = Counter(pool["land_use_type"]).most_common(1)[0][0]

    # --- competitor density ---
    comp_type = "competitor_noodle_asian" if brand == "Marugame Udon" else "competitor_bakery_cake"
    comps = competitors_df[competitors_df["poi_type"] == comp_type].copy()
    comps["dist_km"] = comps.apply(
        lambda r: haversine_km(lat, lon, r["latitude"], r["longitude"]), axis=1
    )
    n_nearby_competitors = int((comps["dist_km"] <= competitor_radius_km).sum())
    if n_nearby_competitors >= 4:
        competitor_density = "high"
    elif n_nearby_competitors >= 2:
        competitor_density = "medium"
    else:
        competitor_density = "low"

    # --- dominant daypart from simulated foot traffic ---
    ft = foot_traffic_df[foot_traffic_df["outlet_id"] == outlet["outlet_id"]]
    daypart_avg = ft.groupby("daypart")["estimated_visits"].mean()
    dominant_daypart = daypart_avg.idxmax()

    # --- occasion flag: The Harvest event-day spikes show as revenue days
    #     far above the outlet's own median; flag if such spikes are common ---
    occasion_flag = None
    if brand == "The Harvest":
        daily_rev = ft.groupby("date")["estimated_revenue_idr"].sum()
        median_rev = daily_rev.median()
        spike_days = (daily_rev > median_rev * 1.5).sum()
        if spike_days >= 2:
            occasion_flag = "birthday_hampers"

    return {
        "outlet_id": outlet["outlet_id"],
        "brand": brand,
        "location_type": outlet["location_type"],
        "city": outlet["city"],
        "dominant_income_bracket": dominant_income,
        "dominant_land_use": dominant_land_use,
        "dominant_daypart": dominant_daypart,
        "competitor_density": competitor_density,
        "occasion_flag": occasion_flag,
    }


# ---------------------------------------------------------------------------
# 2. Rule-based mapping tables (edit these, no code change needed elsewhere)
# ---------------------------------------------------------------------------
BASE_SCENE = {
    "Marugame Udon": "Mangkuk udon hangat dengan topping segar, gaya fast-casual Jepang",
    "The Harvest": "Kue/pastry dengan tampilan bakery boutique, pencahayaan lembut",
}

SETTING = {
    "mall": "Interior mall modern dengan cahaya terang",
    "standalone_ruko": "Fasad toko jalan, suasana neighborhood yang intim",
}

DAYPART_MOOD = {
    "breakfast": "Momen pagi yang segar dan ringan",
    "lunch": "Momen makan siang yang cepat dan mengenyangkan",
    "afternoon": "Momen santai sore, snack/treat casual",
    "dinner": "Momen makan malam yang hangat",
    "late_night": "Momen malam yang santai",
}

LAND_USE_AUDIENCE = {
    "residential": "Audiens keluarga, konteks akhir pekan/santai",
    "office": "Audiens profesional, konteks makan siang cepat",
    "commercial": "Audiens umum urban, konteks jalan-jalan/belanja",
    "mixed": "Audiens urban umum",
}

INCOME_TONE = {
    "high": "Presentasi premium, framing kualitas & pengalaman eksklusif",
    "upper_middle": "Presentasi premium, framing kualitas & pengalaman",
    "middle": "Framing kehangatan & value, kualitas terjaga",
    "lower_middle": "Framing kehangatan & value, tanpa kesan murahan",
    "low": "Framing kehangatan & value, tanpa kesan murahan",
}

COMPETITOR_ANGLE = {
    "high": "Tonjolkan keunikan produk/porsi sebagai pembeda",
    "medium": "Fokus pada produk & suasana",
    "low": "Fokus pada produk & suasana",
}

OCCASION = {
    "birthday_hampers": "Tambahkan elemen hadiah & perayaan pada scene",
}

BRAND_STYLE_GUARDRAIL = {
    "Marugame Udon": "Konsisten dengan identitas visual Marugame Udon (merah-putih, bersih, modern)",
    "The Harvest": "Konsisten dengan identitas visual The Harvest (pastel, homey, boutique)",
}

NEGATIVE_PROMPT = (
    "logo/merek kompetitor, wajah realistis yang identifiable, "
    "klaim diskon/promo yang tidak diotorisasi, teks harga di gambar"
)


# ---------------------------------------------------------------------------
# 3. Assemble the final prompt
# ---------------------------------------------------------------------------
def assemble_prompt(profile):
    segments = [
        BASE_SCENE[profile["brand"]],
        SETTING[profile["location_type"]],
        DAYPART_MOOD[profile["dominant_daypart"]],
        LAND_USE_AUDIENCE[profile["dominant_land_use"]],
        INCOME_TONE[profile["dominant_income_bracket"]],
        COMPETITOR_ANGLE[profile["competitor_density"]],
    ]
    if profile["occasion_flag"] in OCCASION:
        segments.append(OCCASION[profile["occasion_flag"]])
    segments.append(BRAND_STYLE_GUARDRAIL[profile["brand"]])

    return {
        "outlet_id": profile["outlet_id"],
        "brand": profile["brand"],
        "prompt": ". ".join(segments) + ".",
        "negative_prompt": NEGATIVE_PROMPT,
        "insight_profile": profile,
    }


# ---------------------------------------------------------------------------
# MAIN — demo on the dummy dataset
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    outlets = pd.read_csv(os.path.join(DATA_DIR, "outlets.csv"))
    demographics = pd.read_csv(os.path.join(DATA_DIR, "demographics_grid.csv"))
    competitors = pd.read_csv(os.path.join(DATA_DIR, "competitor_pois.csv"))
    foot_traffic = pd.read_csv(os.path.join(DATA_DIR, "foot_traffic_transactions.csv"))

    # one example per brand
    sample_outlets = [
        outlets[outlets.brand == "Marugame Udon"].iloc[0],
        outlets[outlets.brand == "The Harvest"].iloc[0],
    ]

    for outlet in sample_outlets:
        profile = build_insight_profile(outlet, demographics, competitors, foot_traffic)
        result = assemble_prompt(profile)

        print("=" * 70)
        print(f"Outlet: {result['outlet_id']} ({result['brand']})")
        print(f"Insight profile: {result['insight_profile']}")
        print(f"\nPrompt:\n{result['prompt']}")
        print(f"\nNegative prompt:\n{result['negative_prompt']}")
        print()
